spring:
  application:
    name: "product-service"
  data:
    mongodb:
      database: product-service
      port: 27017
      uri: mongodb://localhost:27017

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true